import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'node:querystring';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { migrate, all, get, run } from './db.js';
import './seed.js';

migrate();
const port = process.env.PORT || 3000;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const sessions = new Map();
const statusText = { not_started: 'لم تبدأ', in_progress: 'قيد العمل', done: 'مكتملة' };
const statusClass = { not_started: 'muted', in_progress: 'active', done: 'done' };

function escapeHtml(v = '') { return String(v).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c])); }
function redirect(res, location) { res.writeHead(302, { Location: location }); res.end(); }
function send(res, html, status = 200) { res.writeHead(status, { 'Content-Type': 'text/html; charset=utf-8' }); res.end(html); }
function cookie(req, name) { return req.headers.cookie?.split(';').map(c => c.trim().split('=')).find(([k]) => k === name)?.[1]; }
function currentUser(req) { const id = sessions.get(cookie(req, 'sid')); return id ? get('SELECT * FROM members WHERE id = ?', [id]) : null; }
function requireLogin(req, res) { if (!currentUser(req)) { redirect(res, '/login'); return false; } return true; }
function readBody(req) { return new Promise(resolve => { let body = ''; req.on('data', chunk => body += chunk); req.on('end', () => resolve(parse(body))); }); }
function section(key) { return get('SELECT * FROM project_sections WHERE section_key = ?', [key]) || { title: '', body: '' }; }

function nav(req) {
  const user = currentUser(req);
  const links = [['/','الرئيسية'], ['/dashboard','لوحة التقدم'], ['/tracks','المسارات'], ['/plan','الخطة'], ['/team','الفريق'], ['/chat','المحادثة']];
  return `<nav class="topbar"><a class="brand" href="/">مساحة المشروع</a><div>${links.map(([href,label]) => `<a href="${href}">${label}</a>`).join('')}</div><div class="userbox">${user ? `<span>${escapeHtml(user.name)}</span><form method="post" action="/logout"><button>خروج</button></form>` : '<a class="btn" href="/login">دخول</a>'}</div></nav>`;
}
function layout(req, title, body) { return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(title)}</title><link rel="stylesheet" href="/style.css"></head><body>${nav(req)}<main>${body}</main></body></html>`; }
function taskCard(t) { return `<article class="task"><div><strong>${escapeHtml(t.title)}</strong><p>${escapeHtml(t.description)}</p><small>المسؤول: ${escapeHtml(t.owner || 'غير محدد')} ${t.due_date ? `• الموعد: ${escapeHtml(t.due_date)}` : ''}</small></div><span class="pill ${statusClass[t.status]}">${statusText[t.status]}</span></article>`; }

async function route(req, res) {
  const url = new URL(req.url, `http://${req.headers.host}`);
  if (url.pathname === '/style.css') { res.writeHead(200, { 'Content-Type': 'text/css; charset=utf-8' }); return res.end(fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'))); }

  if (req.method === 'GET' && url.pathname === '/login') return send(res, layout(req, 'تسجيل الدخول', `<section class="auth card"><h1>تسجيل دخول الفريق</h1><p>حساب تجريبي للمشرف: admin@example.com / admin123</p><form method="post"><label>البريد الإلكتروني<input name="email" type="email" required></label><label>كلمة المرور<input name="password" type="password" required></label><button class="primary">دخول</button></form></section>`));
  if (req.method === 'POST' && url.pathname === '/login') { const body = await readBody(req); const user = get('SELECT * FROM members WHERE email = ? AND password = ?', [body.email, body.password]); if (!user) return redirect(res, '/login'); const sid = randomUUID(); sessions.set(sid, user.id); res.writeHead(302, { 'Set-Cookie': `sid=${sid}; HttpOnly; Path=/`, Location: '/dashboard' }); return res.end(); }
  if (req.method === 'POST' && url.pathname === '/logout') { sessions.delete(cookie(req, 'sid')); res.writeHead(302, { 'Set-Cookie': 'sid=; Max-Age=0; Path=/', Location: '/' }); return res.end(); }

  if (req.method === 'GET' && url.pathname === '/') {
    const stats = get("SELECT SUM(status='done') done, SUM(status='in_progress') progress, SUM(status='not_started') pending FROM tasks") || {};
    const latest = get('SELECT notes.*, members.name FROM notes JOIN members ON members.id = notes.member_id ORDER BY created_at DESC LIMIT 1');
    return send(res, layout(req, 'الرئيسية', `<section class="hero"><div><span class="eyebrow">مركز توثيق ومتابعة</span><h1>${escapeHtml(section('idea').title)}</h1><p>${escapeHtml(section('idea').body)}</p><p>${escapeHtml(section('goal').body)}</p><div class="actions"><a class="primary" href="/dashboard">عرض لوحة التقدم</a><a class="secondary" href="/tracks">استكشاف المسارات</a></div></div><aside class="status-card"><h2>الحالة الحالية</h2><ul><li>تم إنجازه: ${stats.done || 0} مهام</li><li>نعمل الآن: ${stats.progress || 0} مهام</li><li>القادم: ${stats.pending || 0} مهام</li></ul>${latest ? `<p class="note">آخر ملاحظة: ${escapeHtml(latest.content)}<br><small>${escapeHtml(latest.name)} • ${latest.created_at}</small></p>` : ''}</aside></section>`));
  }
  if (req.method === 'GET' && url.pathname === '/dashboard') { const stats = get("SELECT SUM(status='done') done, SUM(status='in_progress') progress, SUM(status='not_started') pending FROM tasks") || {}; const note = get('SELECT notes.*, members.name FROM notes JOIN members ON members.id = notes.member_id ORDER BY created_at DESC LIMIT 1'); const msg = get('SELECT messages.*, members.name FROM messages JOIN members ON members.id = messages.member_id ORDER BY created_at DESC LIMIT 1'); return send(res, layout(req, 'لوحة التقدم', `<h1>لوحة متابعة التقدم</h1><section class="grid three"><div class="metric"><b>${stats.done || 0}</b><span>مهام مكتملة</span></div><div class="metric"><b>${stats.progress || 0}</b><span>قيد التنفيذ</span></div><div class="metric"><b>${stats.pending || 0}</b><span>لم تبدأ</span></div></section><section class="grid two"><article class="card"><h2>آخر تحديث</h2><p>${msg ? `${escapeHtml(msg.content)}<br><small>${escapeHtml(msg.name)} • ${msg.created_at}</small>` : 'لا توجد رسائل بعد.'}</p></article><article class="card"><h2>آخر ملاحظة</h2><p>${note ? `${escapeHtml(note.content)}<br><small>${escapeHtml(note.name)} • ${note.created_at}</small>` : 'لا توجد ملاحظات بعد.'}</p></article></section><section class="quick card"><h2>روابط سريعة</h2><a href="/tracks">المسارات</a><a href="/plan">الخطة الزمنية</a><a href="/team">ملاحظات الفريق</a><a href="/chat">المحادثة</a></section>`)); }
  if (req.method === 'GET' && url.pathname === '/tracks') { const researchTasks = all("SELECT tasks.*, members.name owner FROM tasks LEFT JOIN members ON members.id=tasks.owner_id WHERE track='research' ORDER BY updated_at DESC"); const practiceTasks = all("SELECT tasks.*, members.name owner FROM tasks LEFT JOIN members ON members.id=tasks.owner_id WHERE track='practice' ORDER BY updated_at DESC"); const refs = all('SELECT * FROM references_list ORDER BY created_at DESC'); return send(res, layout(req, 'المسارات', `<h1>مسارات المشروع</h1><section class="grid two"><article class="card"><h2>${escapeHtml(section('research').title)}</h2><p>${escapeHtml(section('research').body)}</p><h3>الدراسات والمراجع</h3>${refs.map(r => `<p><a href="${escapeHtml(r.url || '#')}">${escapeHtml(r.title)}</a><br><small>${escapeHtml(r.summary)}</small></p>`).join('')}<h3>تقدم البحث</h3>${researchTasks.map(taskCard).join('')}</article><article class="card"><h2>${escapeHtml(section('practice').title)}</h2><p>${escapeHtml(section('practice').body)}</p><h3>الأدوات والتقنيات</h3><p>Node.js، خادم HTTP مدمج، SQLite، جلسات دخول بسيطة، وواجهة HTML/CSS قابلة للتطوير.</p><h3>المهام العملية</h3>${practiceTasks.map(taskCard).join('')}</article></section>`)); }
  if (req.method === 'GET' && url.pathname === '/plan') { const phases = all('SELECT * FROM phases ORDER BY starts_at'); const tasks = all('SELECT tasks.*, members.name owner FROM tasks LEFT JOIN members ON members.id=tasks.owner_id'); return send(res, layout(req, 'الخطة', `<h1>الخطة الزمنية</h1><section class="timeline">${phases.map(p => `<article class="phase"><header><h2>${escapeHtml(p.name)}</h2><span class="pill ${statusClass[p.status]}">${statusText[p.status]}</span></header><p>${escapeHtml(p.description)}</p><small>${escapeHtml(p.starts_at || '')} — ${escapeHtml(p.ends_at || '')}</small><h3>المهام</h3>${tasks.filter(t => t.phase_id === p.id).map(taskCard).join('') || '<p>لا توجد مهام مرتبطة.</p>'}<h3>المخرجات المتوقعة</h3><p>${escapeHtml(p.expected_outputs)}</p></article>`).join('')}</section>`)); }
  if (req.method === 'GET' && url.pathname === '/team') { if (!requireLogin(req, res)) return; const members = all('SELECT * FROM members ORDER BY is_admin DESC, name'); const notes = all('SELECT notes.*, members.name FROM notes JOIN members ON members.id=notes.member_id ORDER BY created_at DESC'); return send(res, layout(req, 'الفريق', `<h1>الفريق والملاحظات</h1><section class="grid three">${members.map(m => `<article class="member card"><h2>${escapeHtml(m.name)}</h2><p>${escapeHtml(m.role)}</p><small>${escapeHtml(m.bio)}</small></article>`).join('')}</section><section class="card"><h2>إضافة ملاحظة</h2><form method="post" action="/notes" class="stack"><input name="category" placeholder="التصنيف"><textarea name="content" required placeholder="اكتب تحديثك أو فكرتك أو المشكلة..."></textarea><button class="primary">حفظ الملاحظة</button></form></section><section class="feed">${notes.map(n => `<article class="card"><h3>${escapeHtml(n.name)} <small>${escapeHtml(n.category)} • ${n.created_at}</small></h3><p>${escapeHtml(n.content)}</p></article>`).join('')}</section>`)); }
  if (req.method === 'POST' && url.pathname === '/notes') { if (!requireLogin(req, res)) return; const body = await readBody(req); run('INSERT INTO notes (member_id, content, category) VALUES (?, ?, ?)', [currentUser(req).id, body.content, body.category || 'عام']); return redirect(res, '/team'); }
  if (req.method === 'GET' && url.pathname === '/chat') { if (!requireLogin(req, res)) return; const messages = all('SELECT messages.*, members.name FROM messages JOIN members ON members.id=messages.member_id ORDER BY created_at ASC'); return send(res, layout(req, 'المحادثة', `<h1>محادثة الفريق</h1><section class="chat card">${messages.map(m => `<div class="message"><strong>${escapeHtml(m.name)}</strong><p>${escapeHtml(m.content)}</p>${m.attachment_url ? `<a href="${escapeHtml(m.attachment_url)}">رابط / ملف مرفق</a>` : ''}<small>${m.created_at}</small></div>`).join('')}</section><section class="card"><form method="post" action="/messages" class="stack"><textarea name="content" required placeholder="اكتب رسالة أو شارك رابطًا..."></textarea><input name="attachment_url" placeholder="رابط ملف أو مرجع اختياري"><button class="primary">إرسال</button></form></section>`)); }
  if (req.method === 'POST' && url.pathname === '/messages') { if (!requireLogin(req, res)) return; const body = await readBody(req); run('INSERT INTO messages (member_id, content, attachment_url) VALUES (?, ?, ?)', [currentUser(req).id, body.content, body.attachment_url || '']); return redirect(res, '/chat'); }
  return send(res, layout(req, 'غير موجود', '<section class="card"><h1>الصفحة غير موجودة</h1></section>'), 404);
}

http.createServer((req, res) => route(req, res).catch(error => send(res, layout(req, 'خطأ', `<pre>${escapeHtml(error.stack)}</pre>`), 500))).listen(port, () => console.log(`Research team hub running on http://localhost:${port}`));
